// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0i33Is9Lddh7HiBpnMQSZb-dIauibPGI',
    appId: '1:803865433192:web:4eb69915cb0c2e826457dd',
    messagingSenderId: '803865433192',
    projectId: 'myfpayproject',
    authDomain: 'myfpayproject.firebaseapp.com',
    storageBucket: 'myfpayproject.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABO_j9WI66Bn97Byuk_ARjOBggcSLEoGE',
    appId: '1:803865433192:android:328f0391782092c96457dd',
    messagingSenderId: '803865433192',
    projectId: 'myfpayproject',
    storageBucket: 'myfpayproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs_cy5Qzde8sA_mVZlLBf5z4U7cwSeUdQ',
    appId: '1:803865433192:ios:b330791149185dc26457dd',
    messagingSenderId: '803865433192',
    projectId: 'myfpayproject',
    storageBucket: 'myfpayproject.firebasestorage.app',
    iosBundleId: 'com.example.gpya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs_cy5Qzde8sA_mVZlLBf5z4U7cwSeUdQ',
    appId: '1:803865433192:ios:b330791149185dc26457dd',
    messagingSenderId: '803865433192',
    projectId: 'myfpayproject',
    storageBucket: 'myfpayproject.firebasestorage.app',
    iosBundleId: 'com.example.gpya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0i33Is9Lddh7HiBpnMQSZb-dIauibPGI',
    appId: '1:803865433192:web:45c48ecc431c056c6457dd',
    messagingSenderId: '803865433192',
    projectId: 'myfpayproject',
    authDomain: 'myfpayproject.firebaseapp.com',
    storageBucket: 'myfpayproject.firebasestorage.app',
  );
}
